---
# tasks file for regisapp
- name: Ensure application group exists
  group:
    name: "{{ app_group }}"
    system: yes
  when: app_create_user

- name: Ensure application user exists
  user:
    name: "{{ app_user }}"
    group: "{{ app_group }}"
    system: yes
    create_home: no
  when: app_create_user

- name: Ensure configuration directories exist
  file:
    path: "{{ item.path | dirname }}"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: "{{ app_dir_mode }}"
  loop: "{{ app_configs }}"

- name: Manage configuration files
  include_tasks: manage_config.yml
  loop: "{{ app_configs }}"
  loop_control:
    loop_var: app_config
